# Enable split keyboard support
CONFIG_ZMK_SPLIT=y

# Use UART over TRRS for the split link, with no Bluetooth host or split transport.
CONFIG_ZMK_BLE=n
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_WIRED_UART_MODE_INTERRUPT=y
