# Enable split keyboard support
CONFIG_ZMK_SPLIT=y

# Designate this side as the central USB half
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# The name your keyboard will advertise over USB
CONFIG_ZMK_KEYBOARD_NAME="Cosmos"

# Use USB for the host connection and UART over TRRS for the split link.
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=n
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_WIRED_UART_MODE_INTERRUPT=y
